export const ActionType = {
  GET_ACCEPTED_LEAD_LOADING: "GET_ACCEPTED_LEAD_LOADING",
  GET_ACCEPTED_LEAD_FAIL: "GET_ACCEPTED_LEAD_FAIL",
  GET_ACCEPTED_LEAD_SUCCESS: "GET_ACCEPTED_LEAD_SUCCESS",
  GET_INVITED_LEAD_LOADING: "GET_INVITED_LEAD_LOADING",
  GET_INVITED_LEAD_FAIL: "GET_ACCEPTED_LEAD_FAIL",
  GET_INVITED_LEAD_SUCCESS: "GET_INVITED_LEAD_SUCCESS",
};

export const getAcceptedLeadAction = () => {
  return { type: ActionType.GET_ACCEPTED_LEAD_LOADING };
};

export const getInvitedLeadAction = () => {
  return { type: ActionType.GET_INVITED_LEAD_LOADING };
};
